### ISSUE TITLE
json decode error

### ISSUE THREAD

**Issue by narcinexiali** [akasakaid/timefarmtod#3]
Earlier today, I noticed that the script is throwing random errors.
I tried to git pull, but the local repo is already up to day with yours. I tried relaunching it, and it's giving me the same error.
I also tried cloning again, repopulating the data.txt file (I figured maybe the tokens have changed or something) but to no avail.
It seems to me that Time Farm has changed the way their mini app operates, and the response no longer matches what the script expects.

The error I receive is:
```
Traceback (most recent call last):
  File "/home/user/timefarmtod/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/timefarmtod/bot.py", line 324, in <module>
    app.main()
  File "/home/user/timefarmtod/bot.py", line 252, in main
    user_token = self.get_token(data)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/timefarmtod/bot.py", line 172, in get_token
    if "token" not in res.json().keys():
                      ^^^^^^^^^^
  File "/home/user/timefarmtod/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Your help would be appreciated.

**Comment by akasakaid** [comment]
Yeah, because timefarm update his bot. Timefarm data must be fresh / new data, if you want to continue, maybe you will use the login method / use the telethon library.

**Comment by narcinexiali** [comment]
I already pulled the new commit, and am setting it up.
Thank you for looking into the problem quickly.
